[general]
import = [
   # "~/.config/alacritty/themes/alacritty-theme/themes/tokyo_night_storm.toml"
   # "~/.config/alacritty/themes/alacritty-theme/themes/rose_pine.toml"
   # "~/.config/alacritty/themes/alacritty-theme/themes/alabaster_dark.toml"
   # "~/.config/alacritty/themes/alacritty-theme/themes/catppuccin_mocha.toml"
   # "~/.config/alacritty/themes/alacritty-theme/themes/deep_space.toml"
   # "~/.config/alacritty/themes/alacritty-theme/themes/horizon_dark.toml"
   "~/.config/alacritty/themes/alacritty-theme/themes/gruvbox_hard_dark.toml"
]

[terminal.shell]
program = "/bin/zsh"
args = ["-l"]

[colors.cursor]
# cursor = "0xc5c8c6"
# text = "0x1d1f21"

[mouse]
hide_when_typing = true

[font.normal]
family = "MesloLGS Nerd Font Mono"

[font]
size = 14

[window]
decorations = "buttonless"
dynamic_padding = false
# opacity = 0.9
opacity = 1
blur = true
option_as_alt = "both"
startup_mode = "Windowed"

[window.padding]
x = 1
y = 1

[keyboard]
bindings = [
    { key = "8", mods = "Alt|Shift", chars = "{" },
    { key = "9", mods = "Alt|Shift", chars = "}" },
    { key = "8", mods = "Alt", chars = "[" },
    { key = "9", mods = "Alt", chars = "]" },
    { key = "i", mods = "Alt", chars = "|" },
    { key = "'", mods = "Alt", chars = "@" },
    { key = "$", mods = "Alt", chars = "~" },
    { key = "$", mods = "Alt|Shift", chars = "~" },
    # { key = "`", mods = "Alt", chars = "~" },
    { key = "7", mods = "Alt|Shift", chars = '\' },
    { key = "Q", mods = "Command", action = "None" },
    { key = "W", mods = "Command", action = "None" },
]
