import = [
   "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
]

[shell]
program = "/bin/zsh"
args = ["-l"]

[colors.cursor]
# cursor = "0xc5c8c6"
# text = "0x1d1f21"

[font.normal]
family = "MesloLGS Nerd Font Mono"

[font]
size = 16

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.9
blur = true
option_as_alt = "both"
startup_mode = "Windowed"

[window.padding]
x = 1
y = 1

[keyboard]
bindings = [
    { key = "8", mods = "Alt|Shift", chars = "{" },
    { key = "9", mods = "Alt|Shift", chars = "}" },
    { key = "8", mods = "Alt", chars = "[" },
    { key = "9", mods = "Alt", chars = "]" },
    { key = "i", mods = "Alt", chars = "|" },
    { key = "'", mods = "Alt", chars = "@" },
    { key = "7", mods = "Alt|Shift", chars = '\' },
    { key = "Q", mods = "Command", action = "None" },
    { key = "W", mods = "Command", action = "None" },
]
