import = [
    "~/.config/alacritty/themes/themes/gruvbox.toml"
]

[colors.cursor]
# cursor = "0xc5c8c6"
# text = "0x1d1f21"

[colors.primary]
background = "0x1f2f51"
foreground = "0xc5c8c6"

[font.normal]
family = "MesloLGS NF"

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.9
option_as_alt = "both"

[window.padding]
x = 2
y = 2
# opacity = 0.99
# startup_mode = "Windowed"
# padding.x = 10
# padding.y = 20

# decorations = "None"

# decorations = "Full"
# startup_mode = "Maximized"
