[colors.cursor]
cursor = "0xc5c8c6"
text = "0x1d1f21"

[colors.primary]
background = "0x1f2f51"
foreground = "0xc5c8c6"

[font.normal]
family = "MesloLGS NF"

[window]
opacity = 0.95
startup_mode = "Windowed"
padding.x = 10
padding.y = 10

import = [
    "~/.config/alacritty/themes/themes/coolnight.toml"
]

[ env ]
TERM = "xterm-256color"

decorations = "Buttonless"

