import = [
    "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
    # "~/.config/alacritty/themes/themes/gruvbox.toml"
    # "~/.config/alacritty/themes/themes/catppuccin_macchiato.toml"
    # "~/.config/alacritty/themes/themes/palenight.toml"
    # "~/.config/alacritty/themes/themes/snazzy.toml"
    # "~/.config/alacritty/themes/themes/tokyo-night-storm.toml"
    # "~/.config/alacritty/themes/themes/afterglow.toml"

]

[shell]
program = "/bin/zsh"
args = ["-l"]

[colors.cursor]
# cursor = "0xc5c8c6"
# text = "0x1d1f21"

[font.normal]
family = "MesloLGS NF"

[font]
size = 14

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.8
blur = true
option_as_alt = "both"
startup_mode = "Windowed"

[window.padding]
x = 5
y = 5

[keyboard]
bindings = [
    { key = "8", mods = "Alt|Shift", chars = "{" },
    { key = "9", mods = "Alt|Shift", chars = "}" },
    { key = "8", mods = "Alt", chars = "[" },
    { key = "9", mods = "Alt", chars = "]" },
    { key = "i", mods = "Alt", chars = "|" },
]
