theme = "tokyonight_storm"

[editor]
line-number = "relative"
mouse = false
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"


[editor.file-picker]
hidden = false

[editor.whitespace.render]
tab = "all"

[editor.whitespace.characters]
tab = "→"
newline = "⏎"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
C-s = ":w" # Maps Ctrl-s to the typable command :w which is an alias for :write (save file)
A-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
A-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
# config.toml
[keys.normal."C-e"]
y = ":sh zellij run --floating -n 'yazi picker' -- /home/rboynton/.config/fish/scripts/open_in_helix_from_yazi.fish"
