theme = "tokyonight_storm"

[editor]
line-number = "relative"
mouse = false
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"


[editor.file-picker]
hidden = false

[editor.whitespace.render]
# space = "all"
tab = "all"
nbsp = "none"
nnbsp = "none"
newline = "none"

[editor.whitespace.characters]
# space = "·"
tab = "→"
newline = "⏎"
tabpad = "·" # Tabs will look like "→···" (depending on tab width)

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
C-s = ":w" # Maps Ctrl-s to the typable command :w which is an alias for :write (save file)


