# theme = "gruvbox_dark_hard"
# theme = "nightfox"
theme = "tokyonight_moon"

[editor]
line-number = "relative"
mouse = false
bufferline = "always"
auto-save = true
color-modes = true
[editor.smart-tab]
enabled = false

[editor.soft-wrap]
enable = true

[editor.statusline]
left = ["mode", "spinner", "read-only-indicator", "file-modification-indicator"]
center = ["file-name", "version-control"]
right = ["diagnostics", "selections", "position", "total-line-numbers", "file-encoding", "file-line-ending", "file-type"]
separator = "'│'"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.whitespace.render]
space = "all"
tab = "all"
newline = "none"

[editor.whitespace.characters]
space = " "
nbsp = "⍽"    # Non Breaking SPace
# tab = "→"
newline = "⏎"

[editor.indent-guides]
render = true

[editor.lsp]
display-messages = true
snippets = true
# display-inlay-hints = true

[keys.normal]
C-h = "jump_view_left"
C-l = "jump_view_right"
A-s = ["save_selection"]
esc = ["collapse_selection", "keep_primary_selection"]
S-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
S-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
g = { a = "code_action" } # Maps `ga` to show possible code actions
# C-e = [":sh zellij run --floating -n 'yazi picker' -- /Users/blixenkrone/.config/zsh/scripts/open_in_helix_from_yazi.sh"]
C-e = [":sh zellij run -f -x 10% -y 10% --width 80% --height 80% -- bash ~/.config/helix/scripts/yazi-picker.sh"]
C-j = ["page_cursor_half_down"]
C-k = ["page_cursor_half_up"]
y = [":clipboard-yank", "yank"]
"ret" = ["open_below", "normal_mode"] # Maps the enter key to open_below then re-enter normal mode
S-A-f = [":format"]
S-A-s = [":write"]
"{" = ["goto_prev_paragraph", "collapse_selection"]
"}" = ["goto_next_paragraph", "collapse_selection"]
S-x = ["extend_line_up"]

[keys.insert]
"A-<" = "normal_mode"     # Maps Alt-X to enter normal mode
j = { k = "normal_mode"} 
  
[keys.normal.backspace]
g = ":sh zellij run -fc -- lazygit"
f = ":sh zellij run -fc -- y"
t = ":sh zellij run -f -- go test | $(:sh $PWD)"
b = ":sh zellij run -f -- just build"
r = ":sh zellij run -f -- just run"
c = ":wbc"
C = ":bc"
h = ":toggle lsp.display-inlay-hints"
e = { l = ":lsp-workspace-command" }

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
"'" = "'"
'`' = '`'
# '<' = '>'
