# theme = "tokyonight_moon"
# theme = "zed_onedark"
# theme = "catppuccin_mocha"
# theme = "ashen-dev"
theme = "kanagawa_t"

[editor]
line-number = "relative"
mouse = true
bufferline = "always"
auto-save = true
color-modes = true
cursorline = true
true-color = true
undercurl = true
# Minimum severity to show a diagnostic after the end of a line:
end-of-line-diagnostics = "hint"

[editor.inline-diagnostics]
# Minimum severity to show a diagnostic on the primary cursor's line.
# Note that `cursor-line` diagnostics are hidden in insert mode.
cursor-line = "hint"
# Minimum severity to show a diagnostic on other lines:
other-lines = "disable"

[editor.smart-tab]
enable = true

[editor.soft-wrap]
enable = true

[editor.statusline]
left = ["mode", "spinner", "read-only-indicator", "file-modification-indicator"]
center = ["file-name", "version-control"]
right = ["diagnostics", "selections", "position", "total-line-numbers", "file-encoding", "file-line-ending", "file-type"]
separator = "'│'"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
git-ignore = false

[editor.whitespace.render]
space = "all"
tab = "all"
newline = "none"

[editor.whitespace.characters]
space = " "
nbsp = "⍽"    # Non Breaking SPace
# tab = "→"
newline = "⏎"

[editor.indent-guides]
render = true
skip-levels = 0

[editor.lsp]
display-messages = true
snippets = true
# display-inlay-hints = true

[keys.normal]
C-h = "jump_view_left"
C-l = "jump_view_right"
A-e = ["save_selection"]
A-w = [":write"]
"A-<" = [":format"] 
esc = ["collapse_selection", "keep_primary_selection"]
S-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
S-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
C-e = [":sh zellij run -f -x 10%% -y 10%% --width 80%% --height 80%% -- bash ~/.config/helix/scripts/yazi-picker.sh"]
C-f = [":sh zellij run -f -x 10%% -y 10%% --width 80%% --height 80%% -- bash ~/.config/helix/scripts/scooter_replacer.sh"]
# C-y = ":sh zellij run -d right -- bash ~/.config/helix/scripts/yazi-side-picker.sh"
C-j = ["page_cursor_half_down"]
C-k = ["page_cursor_half_up"]
y = [":clipboard-yank", "yank"]
"ret" = ["goto_word", "normal_mode"] # Maps the enter key to open_below then re-enter normal mode
"{" = ["goto_prev_paragraph", "collapse_selection"]
"}" = ["goto_next_paragraph", "collapse_selection"]
S-x = ["extend_line_up"]
# space.F = ["file_picker_in_current_buffer_directory"]

# Macros
space.p = ":pipe sed 's/\\([a-z0-9]\\)\\([A-Z]\\)/\\1_\\2/g' | tr '[:upper:]' '[:lower:]'"
space.x = "@i- <esc>"

# Expansions
space.B = ":echo %sh{git blame -L %{cursor_line},+1 %{buffer_name}}"
space.c = { l = ":sh %sh{echo $PWD | pbcopy}" }


[keys.normal.backspace]
g = ":sh zellij run -fc -- lazygit"
f = ":sh zellij run -fc -- y"
t = ":sh zellij run -f -- go test | $(:sh $PWD)"
b = ":sh zellij run -f -- just build"
r = ":sh zellij run -f -- just run"
c = ":wbc"
C = ":bc"
h = ":toggle lsp.display-inlay-hints"
e = { l = ":lsp-workspace-command" }
s = [
    ":write-all",
    ":insert-output scooter >/dev/tty",
    ":redraw",
    ":reload-all"
]

[keys.insert]
"A-<" = "normal_mode"     # Maps Alt-X to enter normal mode
j = { k = "normal_mode"} 

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
"'" = "'"
'`' = '`'
# '<' = '>'
