# theme = "gruvbox_dark_hard"
# theme = "nightfox"
theme = "tokyonight_moon"

[editor]
line-number = "relative"
mouse = false
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.whitespace.render]
space = "all"
tab = "all"
newline = "none"

[editor.whitespace.characters]
space = " "
nbsp = "⍽"    # Non Breaking SPace
tab = "→"
newline = "⏎"

[editor.lsp]
display-messages = true

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
# C-s = ":w" 
S-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
S-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
g = { a = "code_action" } # Maps `ga` to show possible code actions
C-e = [":sh zellij run --floating -n 'yazi picker' -- /Users/blixenkrone/.config/zsh/scripts/open_in_helix_from_yazi.sh"]
y = [":clipboard-yank", "yank"]
"ret" = ["open_below", "normal_mode"] # Maps the enter key to open_below then re-enter normal mode
S-A-f = [":format"]

[keys.insert]
"A-x" = "normal_mode"     # Maps Alt-X to enter normal mode
j = { k = "normal_mode" } # Maps `jk` to exit insert mode

[keys.normal.backspace]
g = ":sh zellij run -fc -- lazygit"
f = ":sh zellij run -fc -- yy"
t = ":sh zellij run -f -- just test"
b = ":sh zellij run -f -- just build"
r = ":sh zellij run -f -- just run"
