# Language servers

[language-server.gopls]
command = "gopls"

# [language-server.golangci-lint-lsp]
# command = "golangci-lint-langserver"

# [language-server.golangci-lint-lsp.config]
# command = ["golangci-lint", "run", "--output.json.path", "stdout", "--show-stats=false", "--issues-exit-code=1"]

[language-server.scls]
command = "simple-completion-language-server"

[language-server.scls.config]
max_completion_items = 100           # set max completion results len for each group: words, snippets, unicode-input
feature_words = true                 # enable completion by word
feature_snippets = true              # enable snippets
snippets_first = true                # completions will return before snippets by default
snippets_inline_by_word_tail = false # suggest snippets by WORD tail, for example text `xsq|` become `x^2|` when snippet `sq` has body `^2`
feature_unicode_input = false        # enable "unicode input"
feature_paths = false                # enable path completion
feature_citations = false            # enable citation completion (only on `citation` feature enabled)[[language]]

[language-server.sqls]
command = "sqls"

# Languages
[[language]]
name = "go"
roots = ["go.work", "go.mod"]
auto-format = true
comment-token = "//"
language-servers = [ "gopls", "scls" ] # "golangci-lint-lsp"
formatter = { command = "goimports" }

[[language]]
name = "hcl"
injection-regex = "(hcl|tf|nomad)"
language-id = "terraform"
file-types = ["hcl", "tf", "nomad"]
comment-token = "#"
language-servers = [ "terraform-ls" ]
auto-format = true

[[language]]
name = "nix"
auto-format = true
formatter = { command = "terraform-ls" }

[[language]]
name = "html"
file-types = ["html"]
language-servers = ["vscode-html-language-server"]
formatter = { command = 'prettier', args = ["--parser", "html"] }
auto-format = true

[[language]]
name = "json"
formatter = { command = 'prettier', args = ["--parser", "json"] }
auto-format = true

[[language]]
name = "css"
formatter = { command = 'prettier', args = ["--parser", "css"] }
auto-format = true

[[language]]
name = "javascript"
formatter = { command = 'prettier', args = ["--parser", "javascript"] }
# auto-format = true

[[language]]
name = "typescript"
auto-format = true
formatter = { command = 'prettier', args = ["--parser", "typescript"] }

[[language]]
name = "toml"
formatter = { command = "prettier" }
auto-format = true

[[language]]
name = "yaml"
formatter = { command = "prettier" }
auto-format = true

[[language]]
name = "dockerfile"
language-servers = ["docker-langserver"]
auto-format = true

[[language]]
name = "docker-compose"
language-servers = ["yaml-language-server"]
auto-format = true

[[language]]
name = "python"
language-servers = ["pylsp"]
auto-format = true
formatter = {command = 'black', args = ["--quiet", "-"]}

[[language]]
name = "prisma"
language-servers = ["prisma-language-server"]
auto-format = true

[[language]]
name = "sql"
# auto-format = true
comment-token = "--"
# language-servers = ["sqls"]
